-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 01:04:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profil` (
  `idprofil` INT NOT NULL AUTO_INCREMENT,
  `miasto` VARCHAR(25) NULL,
  `plec` INT NULL,
  `wiek` INT NULL,
  `opis` VARCHAR(45) NULL,
  PRIMARY KEY (`idprofil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `hash` VARCHAR(32) NOT NULL,
  `nick` VARCHAR(16) NOT NULL,
  `mail` VARCHAR(20) NOT NULL,
  `id_profilu` INT NOT NULL AUTO_INCREMENT,
  `usercol` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `id_profilu_UNIQUE` (`id_profilu` ASC),
  UNIQUE INDEX `usercol_UNIQUE` (`usercol` ASC),
  CONSTRAINT `idprofil`
    FOREIGN KEY (`id_profilu`)
    REFERENCES `mydb`.`profil` (`idprofil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mes` (
  `idmes` INT NOT NULL,
  `id_tx` INT NULL,
  `id_rx` INT NULL,
  `text` VARCHAR(300) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idmes`),
  INDEX `id_tx_idx` (`id_tx` ASC),
  CONSTRAINT `id_tx`
    FOREIGN KEY (`id_tx`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_rx`
    FOREIGN KEY (`id_rx`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksiazka_adresowa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ksiazka_adresowa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ksiazka_adresowa` (
  `idksiazka_adresowa` INT NOT NULL AUTO_INCREMENT,
  `id_owner` INT NULL,
  `id_friend` INT NULL,
  PRIMARY KEY (`idksiazka_adresowa`),
  UNIQUE INDEX `id_friend_UNIQUE` (`id_friend` ASC),
  UNIQUE INDEX `id_owner_UNIQUE` (`id_owner` ASC),
  UNIQUE INDEX `idksiazka_adresowa_UNIQUE` (`idksiazka_adresowa` ASC),
  CONSTRAINT `id_owner`
    FOREIGN KEY (`id_owner`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_friend`
    FOREIGN KEY (`id_friend`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupa` (
  `idgrupa` INT NOT NULL,
  `admin` INT NULL,
  `member` INT NULL,
  PRIMARY KEY (`idgrupa`),
  INDEX `member_idx` (`member` ASC),
  CONSTRAINT `member`
    FOREIGN KEY (`member`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
